# Konfigurasi Nixpacks Railway (Full Manual)
# providers = [] mematikan deteksi otomatis agar paket default yang rusak tidak ditambahkan
providers = []

[phases.setup]
nixPkgs = [
    'git',                     # Dibutuhkan composer untuk download repo
    'php82',
    'php82Extensions.gd',
    'php82Extensions.pdo',
    'php82Extensions.pgsql',
    'php82Extensions.fileinfo',
    'php82Extensions.zip',
    'php82Extensions.mbstring',
    'php82Extensions.openssl',
    'php82Extensions.tokenizer',
    'php82Extensions.xml',
    'php82Extensions.ctype',
    'php82Extensions.json',
    'php82Extensions.curl',
    'php82Extensions.bcmath',
    'php82Extensions.intl',
    'php82Packages.composer',  # Gunakan versi spesifik ini
    'nodejs_20'                # nodejs_20 SUDAH otomatis menyertakan npm
]

[phases.build]
cmds = [
    'npm install',
    'npm run build',
    'composer install --optimize-autoloader --no-dev --no-interaction --progress --ignore-platform-req=ext-gd',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
