[phases.setup]
# Kita secara eksplisit meminta php82 DAN ekstensinya (termasuk gd)
# Ubah 'php82' menjadi 'php83' jika di composer.json Anda menggunakan PHP 8.3
nixPkgs = [
    'php82', 
    'php82Extensions.gd', 
    'php82Extensions.pdo', 
    'php82Extensions.pgsql', 
    'php82Extensions.fileinfo',
    'php82Extensions.zip',
    'composer', 
    'nodejs_20', 
    'npm'
]

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install',
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
